server.port: 8787

management.endpoints.web.exposure.include: "*"
management.info.env.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client

